image: ruby:2.3.1

before_script:
  - ruby -v
  - which ruby
  - apt update  
  - apt install sudo postgresql
  - pushd kalibro_install && ./install.sh && popd

rspec:
  script:
    - pushd kalibro_configurations && rspec && popd
