image: ruby:2.3.1

services:
  - postgres:latest

before_script:
  - ruby -v
  - which ruby
  - apt update  
  - apt -y install sudo postgresql-client libpq-dev
  - sed -i 's/psql/psql -h postgres/' kalibro_install/install.sh
  - sed -i 's/RAILS_ENVIRONMENT=local/RAILS_ENVIRONMENT=ci/' kalibro_install/install.sh
  - sed -i 's/:test/:test, :ci/g' kalibro_configurations/Gemfile
  - sed -i 's/:ci, require/require/' kalibro_configurations/Gemfile
  - sed -i 's/:test/:test, :ci/g' kalibro_processor/Gemfile  
  - sed -i '/kalibro_configurations_test/a \ \ host\:\ postgres' kalibro_configurations/config/database.yml.sample 
  - sed -i '/kalibro_processor_test/a \ \ host\:\ postgres' kalibro_processor/config/database.yml.sample 
  - pushd kalibro_install ; ./install.sh ; popd

kalibro_configurations:
  script:
    - export RAILS_ENV=ci
    - pushd kalibro_configurations
    - bundle exec rake spec
    - bundle exec rake cucumber
    - popd

kalibro_processor:
  script:
    - export RAILS_ENV=ci
    - pushd kalibro_processor
    - bundle exec rake spec
    - bundle exec rake cucumber
    - popd

