image: ruby:2.3.1

services:
  - postgres:latest

before_script:
  - ruby -v
  - which ruby
  - apt update  
  - apt -y install sudo postgresql-client libpq-dev
  - sed -i 's/psql/psql -h postgres/' kalibro_install/install.sh
  - sed -i 's/RAILS_ENVIRONMENT=local/RAILS_ENVIRONMENT=ci/' kalibro_install/install.sh
  - sed -i 's/:test/:test, :ci/g' kalibro_configurations/Gemfile
  - sed -i 's/:ci, require/require/' kalibro_configurations/Gemfile
  - sed -i 's/:test/:test, :ci/g' kalibro_processor/Gemfile  
  - pushd kalibro_install ; ./install.sh ; popd

rspec:
  script:
    - pushd kalibro_configurations
    - export BUNDLE_GEMFILE=$PWD/Gemfile
    - rake spec
    - popd

