language: ruby

rvm:
  - 2.3.0

before_install:
  - gem install bundler -v 1.11.2
  - pip install radon --user

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
