-
  hosts: mezuro-dev
  become: yes
  roles:
    - database
    - ruby
    - {role: kalibro_configurations, tags: ['kalibro_configurations']}
    - {role: kalibro_processor, tags: ['kalibro_processor']}
    - {role: prezento, tags: ['prezento']}
